vich_uploader:
    db_driver: orm

    mappings:
       product_images:
           uri_prefix: /images/products
           upload_destination: '%kernel.project_dir%/public/images/products'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

       client_image:
           uri_prefix: /media/clients
           upload_destination: '%kernel.project_dir%/public/media/clients'
           namer: Vich\UploaderBundle\Naming\UniqidNamer


